name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger workflow on tag push that starts with 'v'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Extract tag version
        id: extract_tag
        run: |
          echo "Tag from GitHub ref: ${{ github.ref }}"
          TAG=$(echo "${{ github.ref }}" | sed 's/refs\/tags\/v//')
          echo "::set-output name=tag::$TAG"

      - name: Build Docker image
        run: |
          docker build -t sgyamf/s24cicd-Sgyamf:${{ steps.extract_tag.outputs.tag }} .
          docker build -t sgyamf/s24cicd-Sgyamf:latest .

      - name: Push Docker image to DockerHub
        run: |
          docker push sgyamf/s24cicd-Sgyamf:${{ steps.extract_tag.outputs.tag }}
          docker push sgyamf/s24cicd-Sgyamf:latest
